Require a single space after the colon in media features
netsells/stylelint-config-netsells pull request #11
Opened 2018-03-03 14:22 UTC by neveena

## Suggested rule/changes(s):
* `<media-feature-colon-space-after>` : `severity: ERROR`

## Reason for addition/amendment
>*Require a single space after the colon in media features.

@netsells/frontend - Please review

2018-03-03 17:17 UTC, rowancollins89 commented
🦄

2018-03-03 17:21 UTC, samturrell submitted a review, later dismissed

2018-03-03 17:21 UTC, samturrell commented on rules/core/media-feature-colon-space-after/README.md
> +```js
Code block should be css and not js :)

2018-03-05 09:43 UTC, neveena commented
@samturrell made the changes :)

2018-03-09 15:28 UTC, rowbi-wan requested changes

2018-03-09 15:28 UTC, rowancollins89 commented on rules/core/media-feature-colon-space-after/README.md
> +##### 🧟 Example of incorrect code for this rule:
Please change to new file structure. see https://github.com/netsells/stylelint-config-netsells/pull/17 for an example

2018-03-09 17:12 UTC, neveena commented
@rowancollins89 updated the file structure

2018-03-12 07:24 UTC, rowbi-wan commented
Need to generate the readme

2018-03-13 09:09 UTC, neveena commented
@rowancollins89 updated to new format :)

2018-03-13 13:12 UTC, neveena commented
@rowancollins89 made the changes :)

2018-03-13 13:18 UTC, rowbi-wan approved these changes

2018-03-13 13:19 UTC, merged