Adds length-zero-no-unit rule
netsells/stylelint-config-netsells pull request #14
Opened 2018-03-04 22:04 UTC by wik-z

## Suggested rule/changes(s):
* `length-zero-no-unit` : `severity: ERROR`

## Reason for addition/amendment
Disallows units for zero values.

@netsells/frontend - Please review

2018-03-05 15:51 UTC, rowancollins89 commented
Me Likey!

2018-03-05 21:59 UTC, samturrell commented
I'd probably say warning though

2018-03-09 15:29 UTC, rowbi-wan requested changes

2018-03-09 15:29 UTC, rowancollins89 commented on rules/core/length-zero-no-unit/README.md
> +##### 🧟 Example of incorrect code for this rule:
please change to new file structure. see https://github.com/netsells/stylelint-config-netsells/pull/17 for an example

2018-03-13 08:54 UTC, rowbi-wan approved these changes

2018-03-13 08:54 UTC, merged