Adds color-hex-length rule
netsells/stylelint-config-netsells pull request #16
Opened 2018-03-05 21:51 UTC by BeccaAnderton18

## Suggested rule/changes(s):
* `color-hex-length` : `severity: ERROR`

## Reason for addition/amendment
>Enforces hex codes within styles to use long notation as opposed to short notation
>See examples with README.md

@netsells/frontend - Please review

2018-03-06 15:13 UTC, rowancollins89 commented
can someone convince me why `#ffffff` is better than `#fff`?

2018-03-06 15:26 UTC, rowancollins89 commented
can we at least reduce it to a warning rather than a scary ERROR?

2018-03-06 15:31 UTC, BeccaAnderton18 commented
No, because you'll just ignore the warning 😂

2018-03-09 15:30 UTC, rowbi-wan requested changes

2018-03-09 15:30 UTC, rowancollins89 commented on rules/core/color-hex-length/README.md
> +##### 🧟 Example of incorrect code for this rule:
Please change to new file structure. See https://github.com/netsells/stylelint-config-netsells/pull/17 for an example.

2018-03-18 19:47 UTC, samturrell commented
@BeccaAnderton18 Can you convert to new format and change to warning pls :D I don't think anything should be error except things like `!important` or syntax error catchers

2018-03-18 20:31 UTC, samturrell approved these changes

2018-03-18 20:31 UTC, merged